import {display1,Employee,Customer,dis} from './abc';
import {display2,dis as obj1,Customer as XyzCustomer} from './xyz';
display1();
display2();
let emp1 = new Employee();
emp1.dis();
let cc =new Customer();
cc.dis();
dis();
obj1();
let cc1 = new XyzCustomer();
cc1.dis();
